### PR TITLE
Updates for Scala 2.13

### PR DESCRIPTION
**Pull request by travisbrown**
Moved from here: https://github.com/sangria-graphql/sangria-marshalling-testkit/pull/3

MiMa isn't checked automatically as part of the build, but the following commands report no breaking changes:
```
sbt ++2.11.12 mimaReportBinaryIssues
sbt ++2.12.10 mimaReportBinaryIssues
```
Once this is merged I'll publish it as an 1.0.2 release.

### CODE REVIEW

**Review by yanns — APPROVED** [review]
Thx for updating sbt and its plugins at the same time!

**Comment by travisbrown** [comment]
Thanks @yanns! I'm going to go ahead and publish this so we can unblock all the marshalling modules.

**Comment by travisbrown** [comment]
Oh, wait…

**Comment by travisbrown** [comment]
Travis CI didn't run, because I hadn't set it up for this repo yet. Fixing that now.

**Pull request merged**
